CREATE TABLE PRESTADOR_OFERTA_SERVICO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cnpj_prestador VARCHAR(14) NOT NULL,
    id_servico BIGINT NOT NULL,
    quantidade INT NOT NULL,
    data_oferta_servico DATE NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (cnpj_prestador) REFERENCES PRESTADOR_SERVICO(cnpj),
    FOREIGN KEY (id_servico) REFERENCES SERVICOS(id)
)